trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: echo K8S Terraform Azure!
  displayName: 'Run a one-line script'
- task: DownloadSecureFile@1
  name: publickey
  inputs:
    secureFile: 'azure_rsa.pub'
    retryCount: '5'

- task: TerraformInstaller@0
  inputs:
    terraformVersion: 'latest'  # or specify a version like '1.5.7'

- task: TerraformTask@5
  inputs:
    provider: 'azurerm'
    command: 'init'
    workingDirectory: '$(System.DefaultWorkingDirectory)/configuration/iaac/azure/kubernetes'
    commandOptions: '-var client_id=$(cliend_id) -var client_secret=$(client_secret) -var ssh_public_key=$(publickey.secureFilePath)'
    backendServiceArm: 'Azure subscription 1(0d8f7029-620d-48d9-86b5-7a7398fa01d6)'
    backendAzureRmStorageAccountName: 'storageacctrenatoxyz'
    backendAzureRmContainerName: 'storageacctrenatocontainer'
    backendAzureRmKey: 'kubernetes-dev.tfstate'
