trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: echo K8S Terraform Azure!
  displayName: 'Run a one-line script'

- task: DownloadSecureFile@1
  name: publickey
  inputs:
    secureFile: 'azure_rsa.pub'
    retryCount: '5'

- task: TerraformInstaller@0
  inputs:
    terraformVersion: 'latest'

- script: |
    echo "##[group]Authenticating with Service Principal"
    az login --service-principal -u $(AZURE_CLIENT_ID) -p $(AZURE_CLIENT_SECRET) --tenant $(AZURE_TENANT_ID)
    echo "##[endgroup]"
  displayName: 'Authenticate to Azure'

- task: TerraformTask@5
  inputs:
    provider: 'azurerm'
    command: 'init'
    backendType: 'azurerm'
    workingDirectory: '$(System.DefaultWorkingDirectory)/configuration/iaac/azure/kubernetes'
    #commandOptions: '-var client_id=$(client_id) -var client_secret=$(client_secret) -var ssh_public_key=$(publickey.secureFilePath)'
    backendServiceArm: 'azure-resource-manager-service-connection'
    backendAzureRmStorageAccountName: 'storageacctrenatoxyz'
    backendAzureRmContainerName: 'storageacctrenatocontainer'
    backendAzureRmKey: 'kubernetes-dev.tfstate'

#- task: TerraformTask@5
#  inputs:
#    command: 'apply'
#    workingDirectory: '$(System.DefaultWorkingDirectory)/configuration/iaac/azure/kubernetes'
#    commandOptions: '-var ssh_public_key=$(publickey.secureFilePath)'
#    environmentServiceName: 'azure-resource-manager-service-connection'